// Copyright 2016 Hramov Ilya

#ifndef MODULES_VCALC_INCLUDE_VOLUMES_CALCAPP_HPP_
#define MODULES_VCALC_INCLUDE_VOLUMES_CALCAPP_HPP_

class Application {
};

#endif  // MODULES_VCALC_INCLUDE_VOLUMES_CALCAPP_HPP_
